config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  root to: 'tweets#index'
  resources :tweets do
    resources :comments
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :text, presence: true 
end

app/models/relaxation.rb
class Relaxation < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '★' },
    { id: 3, name: '★★' },
    { id: 4, name: '★★★' },
    { id: 5, name: '★★★★' },
    { id: 6, name: '★★★★★' }
  ]


    include ActiveHash::Associations
    has_many :tweets
    
  end

app/models/tasty.rb
class Tasty < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '★' },
    { id: 3, name: '★★' },
    { id: 4, name: '★★★' },
    { id: 5, name: '★★★★' },
    { id: 6, name: '★★★★★' }
  ]


    include ActiveHash::Associations
    has_many :tweets
    
  end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many   :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image
  belongs_to_active_hash :tasty
  belongs_to_active_hash :relaxation
  belongs_to_active_hash :under_ground
  belongs_to_active_hash :wifi


  with_options presence: true do
    validates :coffee_price, format: { with: /\A[0-9]+\z/ }
    validates :tasty
    validates :relaxation
    validates :under_ground
    validates :store_name
    validates :address
    validates :wifi
  end

    # ジャンルの選択が「--」の時は保存できないようにする
    validates :tasty_id, :relaxation_id, :under_ground_id, :wifi_id, numericality: { other_than: 1 }
end

app/models/under_ground.rb
class UnderGround < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '★' },
    { id: 3, name: '★★' },
    { id: 4, name: '★★★' },
    { id: 5, name: '★★★★' },
    { id: 6, name: '★★★★★' }
  ]


    include ActiveHash::Associations
    has_many :tweets

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets
         has_many :comments

         with_options presence: true do
          validates :nickname, length: { maximum: 6 }
         end
        validates :password, length: { minimum: 6 }, confirmation: true
end

app/models/wifi.rb
class Wifi < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '有り' },
    { id: 3, name: '無し' }
  ]
    include ActiveHash::Associations
    has_many :tweets

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.valid?
      @comment.save
      redirect_to tweet_path(@comment.tweet)
    else
      @tweet = @comment.tweet
      @comments = @tweet.comments
      render "tweets/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  before_action :move_to_edit, except: [:index, :show]
  before_action :authenticate_user!, only: [:show, :new, :edit, :destroy, :create]

  def index
    @tweet = Tweet.all.order(id: "DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.valid?
      @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def edit
    @tweet = Tweet.find(params[:id])
    if @tweet.user != current_user
      redirect_to root_path
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:coffee_price, :tasty_id, :relaxation_id, :under_ground_id, :wifi_id, :store_name, :address, :image).merge(user_id: current_user.id)
  end

  def move_to_edit
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, only: [:show]

  def show
    user = User.find(params[:id])
    @name = user.nickname
    @tweets = user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="tweet__image">
  <h1>このアプリの楽しみ方</h1>
  <p>①右上の新規作成押してユーザー登録を行う。</p>
    <img src="/assets/app_ex.png" alt="">
  <p>②ログインしている状態で右上の『つぶやく』クリックする。</p>
    <img src="/assets/app_ex2.png" alt="">
  <p>③お店の情報を（美味しさ度、リラックス度、アンダーグラウン度を最大★５個で評価。）等を入力。最後に画像を選んで『保存する』をクリック！</p>
    <img src="/assets/app_ex3.png" alt="">
  <p>④他のユーザーの詳細ページでコメントを残して情報を共有しよう！</p>
    <img src="/assets/app_ex4.png" alt="">
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ohitorisama</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo10.png", class: :logo), root_path %>
          </div>
          <%= link_to "このアプリの使い方", home_index_path, class: :nav__logout %>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "つぶやく", new_tweet_path, class: :nav__btn %>
            </div> 
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true) do |f|%>

<%= render 'layouts/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :coffee_price, "コーヒー一杯の値段" %><br />
    <%= f.text_field :coffee_price %> 円
  </div>

  <div class="field">
    <%= f.label :tasty_id, "美味しさ度" %><br />
    <%= f.collection_select(:tasty_id, Tasty.all, :id, :name, {}, {class:"select-box", id:"tweet-tasty"}) %>
  </div>
  
  <div class="field">
    <%= f.label :relaxation_id, "リラックス度" %><br />
    <%= f.collection_select(:relaxation_id, Relaxation.all, :id, :name, {}, {class:"select-box", id:"tweet-relaxation"}) %>
  </div>

  <div class="field">
    <%= f.label :under_ground_id, "アンダーグラウン度" %><br />
    <%= f.collection_select(:under_ground_id, UnderGround.all, :id, :name, {}, {class:"select-box", id:"tweet-under_ground"}) %>
  </div>

  <div class="field">
    <%= f.label :wifi_id, "Wi-Fiの有無" %><br />
    <%= f.collection_select(:wifi_id, Wifi.all, :id, :name, {}, {class:"select-box", id:"tweet-wifi"}) %>
  </div>


  <div class="field">
    <%= f.label :store_name, "店名" %><br />
    <%= f.text_area :store_name, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :address, "住所" %><br />
    <%= f.text_area :address, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "コーヒーの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
    <div id="image-list"></div>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="card">
  <%= link_to image_tag(tweet.image, class: :card__img ), tweet_path(tweet.id), method: :get%>
  <div class="card__body">
    <p class="card__summary">
      <%= tweet.store_name %>
    </p>
    <%= link_to tweet.user.nickname, root_path, class: :card__user %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ツイート編集</h2>
      <%= render partial: "form", locals: { tweet: @tweet } %>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting"> 
         ようこそ！
        <%= link_to "#{current_user.nickname}さん", "/users/#{current_user.id}", method: :get, class: :greeting__link%>
        お気に入りのカフェを紹介してください！
      </div> 
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'tweet', collection: @tweet%>
    </div>
  </div>
</main>

app/views/tweets/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { tweet: @tweet } %>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @tweet.store_name%>
      </p>
      <%= link_to @tweet.user.nickname, user_path(@tweet.user.id), class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_tweet_path(@tweet.id), class: :prototype__btn %>
          <%= link_to "削除する", tweet_path(@tweet.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="tweet__image">
        <%= image_tag @tweet.image, class: :card_img %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">コーヒー一杯の値段</p>
          <p class="detail__message">
            <%= @tweet.coffee_price %>円
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">美味しさ度</p>
          <p class="detail__message">
            <%= @tweet.tasty.name %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">リラックス度</p>
          <p class="detail__message">
            <%= @tweet.relaxation.name %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">アンダーグラウン度</p>
          <p class="detail__message">
            <%= @tweet.under_ground.name %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">Wi-Fiの有無</p>
          <p class="detail__message">
            <%= @tweet.wifi.name %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">住所</p>
          <p class="detail__message">
            <%= @tweet.address %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if current_user %>
          <%= form_with model: [@tweet, @comment], local: true do |f|%>
          <%= render 'layouts/error_messages', model: f.object %>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
               <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>
        <ul class="comments_lists">
          <% if @comments %>
            <% @comments.each do |comment| %>
              <li class="comments_list">
                <%= comment.text %>
                <%= link_to comment.user.nickname, user_path(comment.user.id), class: :comment_user %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @name%>さんのつぶやき
      </h2>
      <table class="table">
      <div class="user__card">
        <%= render @tweets %>
      </div>
    </div>
  </div>
</div>